package digital.exchange.me.app;

public enum ReturnEnum
{
    OK,
    NOT_OK,

    ORDER_INVALID,
    ORDER_FULLY_FILLED,
    ORDER_ADDED_TO_ORDERBOOK,
    ORDER_REJECTED,
    ORDERBOOK_EMPTY,

    ORDER_EXISTS,
    ORDER_NOT_EXIST,

    ORDER_CANCELED,

    MATCHING_ENGINE_NOT_EXIST,
    MATCHING_ENGINE_EXISTS,

    ACCOUNT_EXISTS,
    ACCOUNT_NOT_EXIST,

    ACCOUNT_SYMBOL_EXISTS,
    ACCOUNT_SYMBOL_NOT_EXIST,
    ACCOUNT_SYMBOL_INSUFFICIENT_FUNDS
}
