package digital.exchange.me.app.events;

public enum EventId
{
    EVENT_ID_CLOCK_UPDATE,
    EVENT_ID_ME_PAIR_ADDED,
    EVENT_ID_ME_PAIR_REMOVED,
    EVENT_ID_MARKET_ORDER_ADDED,
    EVENT_ID_MARKET_ORDER_CANCELED,
    EVENT_ID_ORDER_FILL,
    EVENT_ID_ACCOUNT_ADDED,
    EVENT_ID_ACCOUNT_REMOVED,
    EVENT_ID_DEPOSIT,
    EVENT_ID_WITHDRAW,
    EVENT_ID_INVALID
}
